# Lecture recordings {.unnumbered}

## Week 1 {.unnumbered}

### Monday {.unnumbered}

Unfortunately, the Monday recording failed :/

### Wednesday {.unnumbered}

{{< video https://youtu.be/6Kl6b3r2uJ4 >}}

## Week 2 {.unnumbered}

### Monday {.unnumbered}

The sound quality is terrible on this one, sorry.

{{< video https://youtu.be/s3vKQY8rntw >}}

### Wednesday {.unnumbered}

The sound quality is terrible on this one, sorry.

{{< video https://youtu.be/IkQZI5XuNVU >}}

## Week 3 {.unnumbered}

### Monday {.unnumbered}

{{< video https://youtu.be/injj7E0_ddI >}}
 
### Wednesday {.unnumbered}

{{< video https://youtu.be/CHcq4_-isTM >}}

## Week 4 {.unnumbered}

### Monday {.unnumbered}

{{< video https://youtu.be/e86mF44Sgyo >}}

### Wednesday {.unnumbered}

The sound is missing from most of this one. The mic battery ran out...

{{< video https://youtu.be/DthrBNwxmiM >}}

## Week 5 {.unnumbered}

## Monday {.unnumbered}

No recording.

<!-- 
{{< video https://youtu.be/ >}}
 -->

### Wednesday {.unnumbered}

{{< video https://youtu.be/Oym9VWLi1ks >}}

## Week 6 {.unnumbered}

### Monday {.unnumbered}

{{< video https://youtu.be/k8EVqg2UXD8 >}}

### Wednesday {.unnumbered}

{{< video https://youtu.be/GCeLRJCsDyU >}}


## Week 7 {.unnumbered}

### Monday {.unnumbered}

{{< video https://youtu.be/cTr7DPec4D8 >}}


### Wednesday {.unnumbered}

{{< video https://youtu.be/H7_UHCayxr4 >}}


## Week 8 {.unnumbered}

### Monday {.unnumbered}

{{< video https://youtu.be/9UR9uqbMSaU >}}

 
### Wednesday {.unnumbered}

This lecture was canceled.


## Week 9 {.unnumbered}

### Monday {.unnumbered}

{{< video https://youtu.be/3HCgpZHHATY >}}


### Wednesday {.unnumbered}

{{< video https://youtu.be/iQNMasqnQi8 >}}

## Week 10 {.unnumbered}

### Monday {.unnumbered}

{{< video https://youtu.be/l4UShr240EU >}}

### Wednesday {.unnumbered}

{{< video https://youtu.be/Cm-A_ybQ10g >}}


## Week 11 {.unnumbered}

### Monday {.unnumbered}

{{< video https://youtu.be/5XwD7EWxtVY >}}

### Wednesday {.unnumbered}

{{< video https://youtu.be/q0usuYKaaaI >}}

<!--

## Week 12 {.unnumbered}

### Monday {.unnumbered}

{{< video https://youtu.be/ >}}


### Wednesday {.unnumbered}

{{< video https://youtu.be/ >}}


## Week 13 {.unnumbered}

### Monday {.unnumbered}

{{< video https://youtu.be/ >}}


### Wednesday {.unnumbered}

{{< video https://youtu.be/ >}}


## Week 14 {.unnumbered}

### Monday {.unnumbered}

{{< video https://youtu.be/ >}}


### Wednesday {.unnumbered}

{{< video https://youtu.be/ >}}

 -->
