
# Preface 

These lecture notes are inspired by the many different books and resources I have used in this course over the years. Especially, "Learning Python the hard way" and "How to think like a computer scientist" have inspired the my onwn notes on programming. These implement the following ideas, which I think best supports learning in an introduction to programming:

1. Each topic and concept is introduced so that it can be applied right away on top of what you know so far.
2. Introduction of each topic covers only the most basic facts and rules required to then learn the rest through practical exercises.

I would like to improve on these notes as much as I can. So you find errors in exercises, that something is poorly explained, that something is redundant, that something is missing, that something would work better in a different ordrer, please let me know. You can do this by [reporting an issue](https://github.com/munch-group/bioinformatics/issues).

Happy coding,<br>
Kasper Munch